### PR TITLE
Design and implement button very cool

### PR DESCRIPTION
**Pull request by drakejacob**
Watch modul page and pateter

### CODE REVIEW

**Comment by daancs** [comment]
Is the "Scroll to top" button in patetpage not included in the cool design button? I thought we talked about this?

**Comment by drakejacob** [comment]
Yes we did, I think I had a reason for not including it, but I can't remember it now. Or maybe I just missed it.

**Comment by daancs** [comment]
We can discuss this later today at the workshop?

**Review by daancs — APPROVED** [review]
lgtm

**Review by daancs — APPROVED** [review]
lgtm

**Pull request merged**
